server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost/8761/eureka/